FROM chromedp/headless-shell:latest

COPY msyh.ttc /usr/share/fonts/

ENTRYPOINT ["dumb-init", "--"]

EXPOSE 9222

ENV PATH /headless-shell:$PATH
ENTRYPOINT [ "/headless-shell/headless-shell", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]