version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8000:8000"

  browser:
    build:
      context: .
      dockerfile: Dockerfile-browser
    ports:
      - "9222:9222"


